# Cask generated by tap/update-cask.sh — DO NOT EDIT.
# ВАЖНО: sha256 — placeholder (B3): .app собирается на macOS
# (tauri build --bundles app,dmg), тарболлы и настоящие sha256 появляются
# после B3. Перегенерировать: release/tap/update-cask.sh <ver>.
cask "wirescale-ui" do
  version "0.1.0"
  desc "menu-bar клиент wirescale (Tauri v2 + Svelte 5)"
  homepage "https://github.com/wirescale"

  if Hardware::CPU.arm?
    url "https://tap.wirescale.org/wirescale-ui-0.1.0-darwin-arm64.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  else
    url "https://tap.wirescale.org/wirescale-ui-0.1.0-darwin-amd64.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  # GUI-клиент требует установленного демона wirescaled (AC-UI-13).
  depends_on formula: "wirescale"

  app "wirescale-ui.app"

  caveats <<~EOS
    Требует формулу wirescale (brew install wirescale). Демон запускается
    через службу: sudo wirescaled service install.
  EOS
end