# Cask generated by tap/update-cask.sh — DO NOT EDIT.
# ВАЖНО: sha256 — placeholder: .app собирается на macOS
# (tauri build --bundles app,dmg --target aarch64-apple-darwin), настоящий
# тарболл и sha появляются после первого прогона release-osx.yml.
# Перегенерировать: release/tap/update-cask.sh <ver>.
cask "wirescale-ui" do
  version "0.1.0"
  desc "menu-bar клиент wirescale (Tauri v2 + Svelte 5)"
  homepage "https://github.com/wirescale"

  # Сборка GUI пока только под Apple Silicon (aarch64-apple-darwin).
  depends_on arch: :arm64
  # GUI-клиент требует установленного демона wirescaled (AC-UI-13).
  depends_on formula: "wirescale"

  url "https://tap.wirescale.org/wirescale-ui-0.1.0-darwin-arm64.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  app "Wirescale.app"

  caveats <<~EOS
    Требует формулу wirescale (brew install wirescale). Демон запускается
    через службу: sudo wirescaled service install.
    Собрано только под Apple Silicon — на Intel-маках cask не установится.
  EOS
end
