# Formula generated by tap/update-formula.sh — DO NOT EDIT.
class Wirescale < Formula
  desc "wirescale — hub-and-spoke VPN: daemon (wirescaled) + CLI (wirescale)"
  homepage "https://github.com/wirescale"
  version "0.0.3.9"

  on_macos do
    on_arm do
      url "https://tap.wirescale.org/wirescale-0.0.3.9-darwin-arm64.tar.gz"
      sha256 "5dad308774c22de1b73e07bbc9e9453f9ec3758b63f072b87d255dc43a801909"
    end
    on_intel do
      url "https://tap.wirescale.org/wirescale-0.0.3.9-darwin-amd64.tar.gz"
      sha256 "c1829e1f155f9e8529dab1c6b0437d8e20f72bdd1f05f4eee5815b1ae85670d0"
    end
  end

  # Демон — Homebrew-сервис (root): sudo brew services start wirescale.
  # Юнит генерирует Homebrew в /Library/LaunchDaemons/sh.brew.wirescale.plist
  # (эквивалент plist от `wirescaled service install`, label wirescale);
  # brew services stop/restart и uninstall-шаг ниже в caveats.
  service do
    run [opt_bin/"wirescaled", "serve"]
    require_root true
    keep_alive true
    environment_variables OSTYPE: "darwin"
  end

  def install
    bin.install "wirescaled", "wirescale", "wirescale-service-undo"

    # shell completion (bash/zsh/fish) — системные каталоги, подхватываются
    # автоматически без правок в ~/.bashrc и ~/.zshrc.
    (bash_completion/"wirescale").write Utils.safe_popen_read(bin/"wirescale", "completion", "bash")
    (zsh_completion/"_wirescale").write Utils.safe_popen_read(bin/"wirescale", "completion", "zsh")
    (fish_completion/"wirescale.fish").write Utils.safe_popen_read(bin/"wirescale", "completion", "fish")
  end

  def caveats
    <<~EOS
      macOS wirescale agent is leaf/spoke only: join a cluster via
      `wirescale peers join <TOKEN>`. Hub/observer are Linux-only.

      The daemon (wirescaled) requires root. Start it with Homebrew services:
        sudo brew services start wirescale
        sudo wirescale-service-undo

      `sudo brew services start` chowns some keg paths root:admin (sticky) so
      the user cannot replace the daemon binary. wirescale-service-undo returns
      ownership to your user, so brew upgrade/uninstall work without sudo rm.

      Before uninstalling, stop the service first (brew uninstall does not):
        sudo brew services stop wirescale
        brew uninstall wirescale

      Upgrading from the old manual unit (wirescaled service install)? Remove
      the old unit first, then start via brew services:
        sudo wirescaled service remove
        sudo brew services start wirescale
    EOS
  end
end
