# Formula generated by tap/update-gui-formula.sh — DO NOT EDIT.
class WirescaleUi < Formula
  desc "menu-bar клиент wirescale (Tauri v2 + Svelte 5)"
  homepage "https://github.com/wirescale"
  version "0.1.0.4"

  # Сборка GUI пока только под Apple Silicon (aarch64-apple-darwin).
  depends_on arch: :arm64
  # GUI-клиенту нужен демон wirescaled (AC-UI-13).
  depends_on "wirescale"

  on_macos do
    url "https://tap.wirescale.org/wirescale-ui-0.1.0.4-darwin-arm64.tar.gz"
    sha256 "3a1eb94e57b11c704f847953e7c82e44b6503b781c9aacee465852dc741280f8"
  end

  def install
    libexec.install "Wirescale.app"
    (bin/"wirescale-ui").write <<~SH
      #!/bin/sh
      exec open "#{opt_libexec}/Wirescale.app" "$@"
    SH
  end

  def caveats
    <<~EOS
      Открыть приложение: wirescale-ui (или напрямую #{opt_libexec}/Wirescale.app)

      Не переноси .app в /Applications вручную — brew upgrade обновляет копию
      в #{opt_libexec}, а перенесённая останется старой.

      Демон требует root (TUN, маршруты, pf):
        sudo wirescaled service install

      Приложение подписано ad-hoc: notarization невозможна (нет Apple
      Developer Program), но Homebrew не ставит карантин на формулы, поэтому
      Gatekeeper приложение не блокирует.
    EOS
  end
end
