# Formula generated by tap/update-formula.sh — DO NOT EDIT.
class Wirescale < Formula
  desc "wirescale — hub-and-spoke VPN: daemon (wirescaled) + CLI (wirescale)"
  homepage "https://github.com/wirescale"
  version "0.0.2.4"

  on_macos do
    on_arm do
      url "https://tap.wirescale.org/wirescale-0.0.2.4-darwin-arm64.tar.gz"
      sha256 "6c50f518f0bf26af80e8cba02e78415285f09245ceafe05bf5fdb9b8ffeb1f2c"
    end
    on_intel do
      url "https://tap.wirescale.org/wirescale-0.0.2.4-darwin-amd64.tar.gz"
      sha256 "9947770a0b5689a2555662b405f365a7f91487007af608e62220079c5c7b1914"
    end
  end

  def install
    bin.install "wirescaled", "wirescale"

    # shell completion (bash/zsh/fish) — системные каталоги, подхватываются
    # автоматически без правок в ~/.bashrc и ~/.zshrc.
    (bash_completion/"wirescale").write Utils.safe_popen_read(bin/"wirescale", "completion", "bash")
    (zsh_completion/"_wirescale").write Utils.safe_popen_read(bin/"wirescale", "completion", "zsh")
    (fish_completion/"wirescale.fish").write Utils.safe_popen_read(bin/"wirescale", "completion", "fish")
  end

  def caveats
    <<~EOS
      macOS wirescale agent is leaf/spoke only: join a cluster via
      `wirescale peers join <TOKEN>`. Hub/observer are Linux-only.

      The daemon (wirescaled) requires root. After install:
        sudo wirescaled service install
        # (service install writes and loads /Library/LaunchDaemons/wirescale.plist itself)
    EOS
  end
end
