# Formula generated by tap/update-gui-formula.sh — DO NOT EDIT.
class WirescaleUi < Formula
  desc "menu-bar клиент wirescale (Tauri v2 + Svelte 5)"
  homepage "https://github.com/wirescale"
  version "0.1.0.8"

  # Сборка GUI пока только под Apple Silicon (aarch64-apple-darwin).
  depends_on arch: :arm64
  # GUI-клиенту нужен демон wirescaled (AC-UI-13).
  depends_on "wirescale"

  on_macos do
    url "https://tap.wirescale.org/wirescale-ui-0.1.0.8-darwin-arm64.tar.gz"
    sha256 "51878e9880979f27dfc32070f4aa424dc1949608491def3c3589b77db28aec7a"
  end

  def install
    # Тарболл содержит ЕДИНСТВЕННЫЙ каталог Wirescale.app/. Homebrew при
    # стейджинге cd'ится внутрь единственного каталога (AbstractDownloadStrategy
    # #chdir), поэтому текущий каталог install — это сам .app. Ставим из корня
    # распаковки относительным путём: mv текущего каталога (Dir.pwd) в песочнице
    # Homebrew падает (ENOENT), а установка обычного дочернего каталога — нет.
    Dir.chdir("..") unless File.directory?("Wirescale.app")
    libexec.install "Wirescale.app"
    (bin/"wirescale-ui").write <<~SH
      #!/bin/sh
      exec open "#{opt_libexec}/Wirescale.app" "$@"
    SH
  end

  def caveats
    <<~EOS
      Открыть приложение: wirescale-ui (или напрямую #{opt_libexec}/Wirescale.app)

      Не переноси .app в /Applications вручную — brew upgrade обновляет копию
      в #{opt_libexec}, а перенесённая останется старой.

      Демон требует root (TUN, маршруты, pf):
        sudo wirescaled service install

      Приложение подписано ad-hoc: notarization невозможна (нет Apple
      Developer Program), но Homebrew не ставит карантин на формулы, поэтому
      Gatekeeper приложение не блокирует.
    EOS
  end
end
