# Formula generated by tap/update-formula.sh — DO NOT EDIT.
class Wirescale < Formula
  desc "wirescale — hub-and-spoke VPN: daemon (wirescaled) + CLI (wirescale)"
  homepage "https://github.com/wirescale"
  version "0.0.2.6"

  on_macos do
    on_arm do
      url "https://tap.wirescale.org/wirescale-0.0.2.6-darwin-arm64.tar.gz"
      sha256 "0733f95536b2a2e772e413f2b89aed90f9601cd95836ede380e889fdeb793678"
    end
    on_intel do
      url "https://tap.wirescale.org/wirescale-0.0.2.6-darwin-amd64.tar.gz"
      sha256 "12f70c58e854183c8912102d9d46366934d2ee013a4d6b2430b8fee71e0435f2"
    end
  end

  def install
    bin.install "wirescaled", "wirescale"

    # shell completion (bash/zsh/fish) — системные каталоги, подхватываются
    # автоматически без правок в ~/.bashrc и ~/.zshrc.
    (bash_completion/"wirescale").write Utils.safe_popen_read(bin/"wirescale", "completion", "bash")
    (zsh_completion/"_wirescale").write Utils.safe_popen_read(bin/"wirescale", "completion", "zsh")
    (fish_completion/"wirescale.fish").write Utils.safe_popen_read(bin/"wirescale", "completion", "fish")
  end

  def caveats
    <<~EOS
      macOS wirescale agent is leaf/spoke only: join a cluster via
      `wirescale peers join <TOKEN>`. Hub/observer are Linux-only.

      The daemon (wirescaled) requires root. After install:
        sudo wirescaled service install
        sudo launchctl load /Library/LaunchDaemons/wirescale.plist
    EOS
  end
end
